 const SEARCH_COUNTRY_SUCCESS = 'SEARCH_COUNTRY_SUCCESS';
 const SEARCH_COUNTRY_ERROR = 'SEARCH_COUNTRY_ERROR';
 const ALL_COUNTRIES_SUCCESS = 'FETCH_ALL_COUNTRIES_SUCCESS';
 const ALL_COUNTRIES_ERROR = 'FETCH_ALL_COUNTRIES_ERROR';

export {SEARCH_COUNTRY_SUCCESS ,SEARCH_COUNTRY_ERROR,ALL_COUNTRIES_SUCCESS , ALL_COUNTRIES_ERROR}


